'''
This document contains an algorithm to compute Theta(Q1, Q2), 
as defined in my msc thesis. 
Author: Felix Kalker

EXAMPLES: 
'''


# This file was *autogenerated* from the file Theta.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_53 = Integer(53); _sage_const_4 = Integer(4); _sage_const_0p5 = RealNumber('0.5'); _sage_const_3 = Integer(3)
def principal_root(Q):
    '''
    Returns the principal root (-b + sqrt(disc))/2a, represented as an element 
    of the number field K = Q(sqrt(disc)) with the embedding sqrt(disc) > 0
    '''
    a, b, c = Q
    disc = Q.discriminant()
    generator_name = 'sqrt' + str(disc)
    K = NumberField(x**_sage_const_2 -disc, generator_name, embedding=RR(sqrt(disc)))
    sqrtdiscQ = K.gen()
    return((-b + sqrtdiscQ)/(_sage_const_2 *a))

def other_root(Q):
    '''
    Returns the conjugate  (-b - sqrt(disc))/2a of the principal root, represented as an element 
    of the number field K = Q(sqrt(disc)) with the embedding sqrt(disc) > 0
    '''
    a, b, c = Q
    disc = Q.discriminant()
    generator_name = 'sqrt' + str(disc)
    K = NumberField(x**_sage_const_2 -disc, generator_name, embedding=RR(sqrt(disc)))
    sqrtdiscQ = K.gen()
    return((-b - sqrtdiscQ)/(_sage_const_2 *a))

    def find_cycle(Q):
    '''
    Given a reduced binary form, with positive discriminant, find: 
    - the cycle of reduced forms, 
    - the cycle of nearly reduced forms, 
    - the automorph
    - the automorph written as a word in S and T

    See Appendix A of my master's thesis for an extensive explanation of this 
    algorithm. 
    
    INPUT: 
    - a reduced binary quadratic form Q = <a, b, c> (i.e. ac < 0 and b > |a + c|)
    
    OUTPUT
    - a list of all reduced forms equivalent to Q
    - a list of all nearly reduced forms equivalent to Q (ac < 0)
    - the automorph of Q (with trace > 2 and with the eigenspace (-b + sqrt(b^2 - 4ac), 2) associated to the eigenvalue > 1)
    - the automorph written as a word in S and T
    
    We compute these by performing the reduction algorithm to Q until we return to our original Q. 
    Along the way we keep track of the transformations we have applied to Q to find its automorph, 
    and also a representation of this automorph as a word in S and T. 
    We run in to all the reduced forms that are equivalent to Q along the way. 
    Each nearly reduced form lies between two reduced forms or its inversion does. 
    
    EXAMPLES:
    
    '''
    if not Q.is_reduced():
        raise ValueError('%s is not reduced' % Q)
    if not Q.discriminant() > _sage_const_0 :
        raise ValueError('%s should have positive discriminant' % Q)
    
    S = matrix(ZZ, [[_sage_const_0 , -_sage_const_1 ], [_sage_const_1 , _sage_const_0 ]])
    T = matrix(ZZ, [[_sage_const_1 , _sage_const_1 ], [_sage_const_0 , _sage_const_1 ]])
    
    assert Q.is_reduced()
    reduced_orbit = []
    nearly_reduced_orbit = []
    automorph = Matrix(ZZ, [[_sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 ]])
    automorph_word_in_S_and_T = ''
    rounded_sqrt_disc = Q.discriminant().sqrt(prec=_sage_const_53 ).floor()
    
    original_Q = Q
    while True:
        # invert Q
        reduced_orbit.append(Q)
        print(principal_root(Q).n())
        [a, b], [c, d] = automorph
        print((c * principal_root(Q) + d).n())
        print()
        Q = Q.matrix_action_right(S)
        automorph = automorph * S
        automorph_word_in_S_and_T += ' S'
    
        # translate Q to a reduced form
        
        (a, b, c) = Q
        n = ((-b + rounded_sqrt_disc)/(_sage_const_2 *abs(a))).floor()
        for i in range(n):
            Q = Q.matrix_action_right(T**sign(a))

            
            # Each nearly reduced form either lies between two reduced forms, 
            # or its inversion does
            nearly_reduced_orbit.append(Q)
            nearly_reduced_orbit.append(Q.matrix_action_right(S)) 
        
        automorph = automorph * T**(sign(a)*n)
        automorph_word_in_S_and_T += ' T^%s' % (sign(a)*n)
    
        #assert Q.is_reduced()
        
        if (Q == original_Q): # we have completed the cycle
            
            if automorph.trace() < _sage_const_0 :
                # replace automorph to -automorph
                automorph = -automorph
                automorph_word_in_S_and_T += ' S S'
    
            #[a, b], [c, d] = automorph
            #assert c*principal_root(Q) + d > 1
            
            return(reduced_orbit, nearly_reduced_orbit, automorph, automorph_word_in_S_and_T)
            
                
def class_group_representatives(disc):
    '''
    Given a positive discriminant that is not a square,
    gives a set of representatives for the set of binary quadratic 
    forms of that discriminant modulo the action of SL2Z
    
    INPUT: 
    - `disc`: an integer > 0 not a square
    
    OUTPUT: 
    - A list of binary quadratic forms representing the set of binary quadratic 
    forms with discriminant `disc` modulo the action of SL2Z
    
    ALGORITHM: 
    The discriminant of Q = <a, b, c> is b^2 - 4ac. Each binary quadratic form 
    is equivalent to a reduced form (i.e. a form with ac < 0 and b > |a + c|)
    We loop over all values of b with 0 < b < sqrt(disc) and then the possibilities of a
    are the divisors of (disc - b^2)/4. We check if we have not seen an equivalent form before 
    and add Q = <a, b, (b^2 - disc)/4a> otherwise. 
    '''
    if disc <= _sage_const_0 :
        raise ValueError('Algorithm not implemented for negative discriminants')
    if ZZ(disc).is_square(): 
        raise ValueError('Algorithm not implemented for square discriminants')
    if disc % _sage_const_4  not in [_sage_const_0 , _sage_const_1 ]:
        return([])
    
    reduced_forms = []
    reduced_cycles_representatives = []
    for b in range(_sage_const_1 , ceil(sqrt(disc))):
        if not b % _sage_const_2  == disc % _sage_const_2 : 
            continue
        
        ac = (b**_sage_const_2  - disc)/_sage_const_4 
        positive_divisors = divisors(ac)
        all_divisors = positive_divisors + [-k for k in positive_divisors]

        for a in divisors(ac):
            #positive a:
            c = ac/a
            Q = BinaryQF(a, b, c)
            #print(Q)
            if b <= (a + c).abs() or gcd([a, b, c]) != _sage_const_1  or Q in reduced_forms:
                continue
            
            Qcycle = find_cycle(Q)[_sage_const_0 ]
            reduced_forms += Qcycle
            reduced_cycles_representatives.append(Q)
            
    return(reduced_cycles_representatives)  

def compute_xi(nearly_reduced_orbit):
    '''
    Computes the constant xi as described in Lemma 2.1 from 
    'Singular moduli for real quadratic fields: a rigid analytic approach' by Darmon and Vonk
    
    INPUT: 
    a list of all nearly reduced forms equivalent to some binary quadratic form
    '''
    xi = _sage_const_1 
    for Q in nearly_reduced_orbit:
        a, b, c = Q
        if a > _sage_const_0 : #this means root_Q = (-b + sqrt(b^2-4*a*c))/2*a > 0
            root_Q = principal_root(Q)
            assert root_Q > _sage_const_0 
            xi *= root_Q
    return(xi)

def compute_naive_knopp(nearly_reduced_orbit):
    '''
    Computes the value bar{j^circ_tau} from Lemma 2.1 from 
    'Singular moduli for real quadratic fields: a rigid analytic approach' by Darmon and Vonk
    '''
    K = principal_root(nearly_reduced_orbit[_sage_const_0 ]).parent()
    sqrtdisc = K.gen()
    Kz = PolynomialRing(K, names=('z',)); (z,) = Kz._first_ngens(1)
    naive_knopp = Kz(_sage_const_1 )
    for Q in nearly_reduced_orbit:
        a, b, c = Q
        root_Q = (-b + sqrtdisc)/(_sage_const_2 *a)
        
        naive_knopp *= (z-root_Q)**(sign(a))
        
    return(naive_knopp)

def compute_Knopp_in_S_and_T(Q):
    '''
    Computes the values of Kn_Q(S) and Kn_Q(T) using Lemma 2.2 of [DV]
    
    INPUT: 
    - an indefinite binary quadratic form Q
    '''


    #print(disc)
            
    Q = Q.reduced_form()
    reduced_orbit, nearly_reduced_orbit, automorph, automorph_word_in_S_and_T = find_cycle(Q)
    xi = compute_xi(nearly_reduced_orbit)
    tau_Q = principal_root(Q)
    [a, b], [c, d] = automorph
    unit = (c*tau_Q + d)**-_sage_const_1 

    naive_knopp = compute_naive_knopp(nearly_reduced_orbit)
    Kz = naive_knopp.parent()
    
    KnoppS = naive_knopp / xi
    KnoppT = Kz(unit) 
    
    return(KnoppS, KnoppT)

def left_slash_action(matrix, rational_function, weight=_sage_const_0 ):
    '''
    Given a matrix gamma in SL2Z and a rational function f(z), 
    computes gamma * f(z)
    
    INPUT: 
     - a matrix gamma in SL2Z
     - a rational function f
    (- the weight of the action)
    '''
    #print(rational_function.parent())
    z = rational_function.parent().gen()
    [a, b], [c, d] = matrix**-_sage_const_1 
    return((c*z+d)**-weight * rational_function((a*z + b)/(c*z + d)))


def evaluate_Knopp_in_matrix(KnoppS, KnoppT, matrix_as_word):
    '''
    Computes the value of the Knopp cocycle in a matrix using the cocycle relation 
    and its values in the generators S, T of SL2Z. 
    
    INPUT:
    - 
    '''
    Kz = KnoppS.parent()
    
    cumulative_matrix = matrix([[_sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 ]])
    Knopp = Kz(_sage_const_1 )
    for SorTn in matrix_as_word: #run through the S and T^n from left to right
        # Repeatedly use the equality 
        # Kn(alpha_1 ... alpha_n beta) = Kn(alpha_1 ... alpha_n) times ((alpha_1 ... alpha_n) star Kn(beta))
        if SorTn == 'S': 
            S = matrix([[_sage_const_0 , -_sage_const_1 ], [_sage_const_1 , _sage_const_0 ]])
            Knopp *= left_slash_action(cumulative_matrix, KnoppS)
            cumulative_matrix = cumulative_matrix * S
        else: #matrix is of the form 'T^n'
            n = ZZ(SorTn[_sage_const_2 :])
            Tn = matrix([[_sage_const_1 , n], [_sage_const_0 , _sage_const_1 ]])
            cumulative_matrix = cumulative_matrix * Tn
            Knopp *= KnoppT**n
        
        #print(cumulative_matrix)
        #print(Knopp)
    return(Knopp)

def write_matrix_as_word(gamma):
    '''
    Given a matrix in SL2Z, write it as a word in S and T (represented as a string)
    '''
    QI = NumberField(x**_sage_const_2 +_sage_const_1 , names=('I',)); (I,) = QI._first_ngens(1)
    [a, b], [c, d] = gamma**-_sage_const_1 
    tau = (a*_sage_const_2 *I + b)*(c*_sage_const_2 *I + d)**-_sage_const_1  # = gamma^-1 2i
    word = ''
    
    reconstructed_gamma = matrix([[_sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 ]])
    S = matrix([[_sage_const_0 , -_sage_const_1 ], [_sage_const_1 , _sage_const_0 ]])
    T = matrix([[_sage_const_1 , _sage_const_1 ], [_sage_const_0 , _sage_const_1 ]])
    # applying the reduction algorithm to tau to move it back to the fundamental domain
    
    while not (tau.norm() >= _sage_const_1  and tau[_sage_const_0 ].abs() <= _sage_const_0p5 ):
        if tau.norm() < _sage_const_1 :
            # inverting
            tau = -tau**-_sage_const_1 
            word = 'S ' + word
            reconstructed_gamma = S*reconstructed_gamma
            
        # translating    
        n = - round(tau[_sage_const_0 ])
        tau = tau + n
        if n != _sage_const_0 :
            word = ('T^%s ' % n) + word
            reconstructed_gamma = T**n*reconstructed_gamma
    
    # we now have the right representation up to sign
    if reconstructed_gamma == -gamma:
        word = 'S S ' + word
    else:
        assert reconstructed_gamma == gamma
    
    return(word)


def Knopp_cocycle(Q, gamma):
    '''
    Computes the value of the Knopp cocycle Kn_Q in the matrix gamma by first computing 
    the value of Kn_Q in S and T and then using the cocyle relation
    '''
    Q = Q.reduced_form()
    KnQS, KnQT = compute_Knopp_in_S_and_T(Q)
    
    #we make sure gamma is in the correct form:
    if type(gamma) == str:
        gamma = gamma.split()
        
    if  type(gamma) != list:
        # gamma is a matrix and we need to write it as a word in S and T
        gamma = write_matrix_as_word(gamma).split()
        
    return(evaluate_Knopp_in_matrix(KnQS, KnQT, gamma))
               

    
    
def Theta(Q1, Q2):
    '''
    Computes Theta(Q1, Q2) as defined in my thesis. It is equal to Kn_{Q1}[Q2] = Kn_{Q1}(gamma_Q2)(root_Q2)
    
    INPUT: 
     - two binary quadratic forms with non-square positive discriminants
    
    EXAMPLES: 
    '''
    Q1 = Q1.reduced_form()
    Q2 = Q2.reduced_form()

    
    automorph_of_Q2_as_word_in_S_and_T = find_cycle(Q2)[_sage_const_3 ].split()
    KnQ1gammaQ2 = Knopp_cocycle(Q1, automorph_of_Q2_as_word_in_S_and_T)
    disc1 = Q1.discriminant()
    disc2 = Q2.discriminant()
    generator_name_K1 = 'sqrt' + str(disc1)
    generator_name_K2 = 'sqrt' + str(disc2)
    K1 = NumberField(x**_sage_const_2  - disc1, generator_name_K1, embedding=RR(sqrt(disc1)))
    
    K2 = NumberField(x**_sage_const_2  - disc2, generator_name_K2, embedding=RR(sqrt(disc2)))
    L = K1.composite_fields(K2, 'a')[_sage_const_0 ]
    sqrtdisc1 = L(K1.gen()) 
    sqrtdisc2 = L(K2.gen())
    
        # this compositum has generator a, which is equal to sqrt(discG) + n*sqrt(discF)
        # for some integer n
    a, b, c = Q2
    root_Q2 = (-b + sqrtdisc2)/(_sage_const_2 *a)
        
    return(KnQ1gammaQ2(root_Q2))

